# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c5e4b249d784dde6741943200a5390ca15a441274950d5892a0dae7b945002df774a3efbb761d51b73c8ad87107d0ef03a3a898aafd1081fa663452c75f8e8b

test:
  secret_key_base: 2cbff712e16f9129567a776a4f613a0c00ef3bafca41528ed8a4aa818410ce6a56591320809c1864ee8d89a32085ff0c0082b8656930ea3f92ef791006c93799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
